# Generated by Django 5.1.2 on 2024-11-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('token', models.CharField(max_length=6)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('usage', models.CharField(choices=[('register', 'register'), ('reset', 'reset')], max_length=10)),
            ],
        ),
    ]
