# Generated by Django 5.1.2 on 2024-11-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordToken',
            new_name='VerificationCode',
        ),
    ]
