# Generated by Django 5.1.2 on 2024-11-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
